---
all:
  hosts:
    ahost: 
  children:
    cluster:
      hosts:
        hmaster01:
        hmaster02:
        hslave01:
        hslave02:
        monitor01:
    elasticsearch:
      hosts:
        monitor01:
    kibana:
      hosts:
        monitor01:
    logstash:
      hosts:
        monitor01:
    hdnodes:
      hosts:
        hmaster01:
        hmaster02:
        hslave01:
        hslave02:
    zookeepers: # minimal 3, must be odd number of hosts
      hosts:
        hmaster01:
          zookeeper_id: 1
        hmaster02:
          zookeeper_id: 2
        hslave01:
          zookeeper_id: 3

