---
all:
  hosts:
    ahost: 
  children:
    cluster:
      hosts:
        hmaster01:
        hmaster02:
        hslave01:
        hslave02:
        monitor01:
    elasticsearch:
      hosts:
        monitor01:
    kibana:
      hosts:
        monitor01:
    logstash:
      hosts:
        monitor01:

