---
# Site Configuration
# ==================

- hosts: cluster 
  user: ansibler
  tasks:
    - name: determinei network interface
      set_fact: ipv4_address="{{ hostvars[inventory_hostname].ansible_eth1.ipv4.address }}"
      # eg. to use a eth1: ipv4_address="{{ hostvars[inventory_hostname].ansible_eth1.ipv4.address }}"

# cluster cross cutting components

- hosts: cluster
  user: ansibler
  sudo: true
  roles:
    - common
    # ganglia_monitor is not working at moment
    #- ganglia_monitor


- hosts: all
  user: ansibler
  sudo: true
  roles:
    - { role: oracle_jdk, when: jdk_installed is not defined }



- hosts: elasticsearch
  user: ansibler
  sudo: true
  roles:
    - elasticsearch
    #- elasticsearch_curator

- hosts: kibana
  user: ansibler
  sudo: true
  roles:
    - kibana

- hosts: logstash
  user: ansibler
  sudo: true
  roles:
    - logstash


- hosts: all
  user: ansibler
  sudo: true
  roles:
    - td_agent

# Hadoop

# Add cdh repo and key

- hosts: hdnodes
  user: ansibler
  sudo: true
  roles:
    - cdh_common


- hosts: zookeepers
  user: ansibler
  sudo: true
  roles:
    - cdh_zookeeper

- hosts: journalnodes
  user: ansibler
  sudo: true
  roles:
    - cdh_hadoop_hdfs_journalnode

- hosts: resourcemanager
  user: ansibler
  sudo: true
  roles:
    - cdh_hadoop_yarn_resourcemanager

- hosts: namenodes
  user: ansibler
  sudo: true
  roles:
    - cdh_hadoop_hdfs_namenode
    - cdh_hadoop_hdfs_zkfc

- hosts: nodemanagers
  user: ansibler
  sudo: true
  roles:
    - cdh_hadoop_yarn_nodemanager


- hosts: datanodes
  user: ansibler
  sudo: true
  roles:
    - cdh_hadoop_hdfs_datanode

- hosts: nodemanagers
  user: ansibler
  sudo: true
  roles:
    - cdh_hadoop_mapreduce

- hosts: historyserver
  user: ansibler
  sudo: true
  roles:
    - cdh_hadoop_mapreduce_historyserver
    - cdh_hadoop_yarn_proxyserver

# config all components 
- hosts: hdnodes
  user: ansibler
  sudo: true
  roles:
    #- cdh_hadoop_config

