---
startDelaySeconds: 0
#hostPort: 127.0.0.1:{{jmx_prometheus_exporter_port}}
#jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:{{jmx_prometheus_exporter_port}}/jmxrmi
ssl: false
lowercaseOutputName: false
lowercaseOutputLabelNames: false
#whitelistObjectNames: ["org.apache.hadoop.metrics2:*"]
#blacklistObjectNames: ["org.apache.hadoop.metrics2:type=ColumnFamily,*"]
rules:
  - pattern: 'org.apache.hadoop.metrics2<type=(\w+), name=(\w+)><>Value: (\d+)'
    name: hadoop_$1_$2
    value: $3
    valueFactor: 0.001
    labels: {}
    help: "hadoop metrics2 $1 $2"
    type: GAUGE
    attrNameSnakeCase: false

