---
# file: roles/cdh_hadoop_yarn_nodemanager/tasks/main.yml


- name: install hadoop-yarn-nodemanager via apt
  apt: name=hadoop-yarn-nodemanager
  tags: hadoop

- name: create the /data/yarn/local directory
  file: path=/data/yarn/local owner=yarn group=yarn state=directory
  tags: hadoop

- name: create the /data/yarn/logs directory
  file: path=/data/yarn/logs owner=yarn group=yarn state=directory
  tags: hadoop


