---
# file: roles/cdh_zookeeper/tasks/main.yml
- name: run this to avoid install zookeeper from os,which runs default priority of 500
  template: src=cloudera.pref dest=/etc/apt/preferences.d/cloudera.pref 
  tags: zookeeper
 
  

- name: install zookeeper-server via apt, it is at /etc/zookeeper
  apt: name={{ item }} force=yes update-cache=yes
  with_items:
    - zookeeper
    - zookeeper-server
  tags: zookeeper


- name: install zookeeper via apt, it is at /etc/zookeeper
  apt: name=zookeeper force=yes update-cache=yes
  tags: zookeeper

- name: install zookeeper-server via apt, it is at /etc/zookeeper
  apt: name=zookeeper-server force=yes update-cache=yes
  tags: zookeeper


- name: create data directory /var/lib/zookeeper directory
  file: path=/var/lib/zookeeper owner=zookeeper group=zookeeper state=directory
  tags: zookeeper




- name: configure ZooKeeper in /etc/zookeeper/conf/zoo.cfg
  template: src=zoo.cfg dest=/etc/zookeeper/conf/zoo.cfg owner=zookeeper group=zookeeper mode=0644
  notify:
    - restart zookeeper
  tags: zookeeper

- name: initialize ZooKeeper
  command: creates=/var/lib/zookeeper/myid service zookeeper-server init --myid={{ zookeeper_id }}
  tags: zookeeper




