---
# file: roles/ganglia_monitor/handlers/main.yml

# for some reason gmond hangs when restarting it on Ubuntu 12.04+, use kill here
- name: restart ganglia-monitor
  service: name=ganglia-monitor state=restarted

