---
# file: roles/cdh_hadoop_yarn_resourcemanager/tasks/main.yml

- name: install hadoop-yarn-resourcemanager via apt
  apt: name=hadoop-yarn-resourcemanager
  tags: hadoop

- name: configure rsyslog for hadoop-yarn-resourcemanager
  template: src=rsyslog.conf dest=/etc/rsyslog.d/60-hadoop-yarn-resourcemanager.conf owner=root group=root mode=0644
  tags: rsyslog
  notify:
    - restart rsyslog
