---

# file: roles/oracle_jdk/tasks/main.yml

- name: debian | ubuntu | add java ppa repo
  apt_repository:
    repo=ppa:webupd8team/java
    state=present
  when: ansible_distribution == 'Ubuntu'
  tags: java

- block:
  - name: debian | ensure the webupd8 launchpad apt repository key is present
    apt_key:
      id=0xC2518248EEA14886
      keyserver=keyserver.ubuntu.com
      state=present

  - name: debian | ensure the webupd8 launchpad apt repository is present
    apt_repository:
      repo="{{ item }} http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main"
      update_cache=yes
      state=present
    with_items:
      - deb
      - deb-src

  when: ansible_distribution == 'Debian'
  tags: java

- name: debian | set license as accepted
  debconf: name='oracle-java{{ oracle_java_version }}-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  tags: java


- name: debian | ensure Java is installed
  apt:
    name="oracle-java{{ oracle_java_version }}-installer"
    state={{ oracle_java_state }}
    cache_valid_time={{ oracle_java_cache_valid_time }}
    update_cache=yes
  tags: java

- name: debian | set Java version as default
  apt:
    name="oracle-java{{ oracle_java_version }}-set-default"
    state=latest
  when: oracle_java_set_as_default
  tags: java


- name: set fact jdk_installed
  set_fact: jdk_installed=true
  tags: java

