---
# file: roles/elasticsearch/tasks/main.yml

- name: install Elasticsearch
  shell: creates=/usr/share/elasticsearch/bin/elasticsearch chdir=/tmp wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.1.1.deb && dpkg -i elasticsearch-6.1.1.deb
  tags: elasticsearch

- name: config Elasticsearch
  template: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml
  tags: elasticsearch
  notify:
    - restart elasticsearch 
 
- name: make sure Elasticsearch is enabled and started
  service: name=elasticsearch enabled=yes state=started
  tags: elasticsearch

#- name: install Elasticsearch marvel plugin
#  command: creates=/usr/share/elasticsearch/plugins/marvel chdir=/usr/share/elasticsearch/bin ./plugin -install elasticsearch/marvel/latest
#  tags: elasticsearch
#  notify:
#    - restart elasticsearch


