---
global:
  scrape_interval: 15s

# add Prometheus itself to list of exporters to scrape
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

# scrape node_exporter on same machine
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']

# scrape jmx_exporter_hadoop 
  - job_name: 'hadoop_jmx'
    scrape_interval: 5s
    static_configs:
      - targets: [{% for host in groups["hdnodes"] %}'{{ host }}:{{ jmx_prometheus_exporter_port }}'{% if not loop.last %},{% endif %}{% endfor %}]
