---
# file: roles/ganglia_monitor/tasks/main.yml


- name: install Ganglia Monitor and required packages via apt
  apt: name={{ item }}
  with_items:
    - ganglia-monitor
    - ganglia-monitor-python

- name: configure gmond.conf in /etc/ganglia/gmond.conf
  template: src=gmond.conf dest=/etc/ganglia/gmond.conf owner=root group=root mode=0644
  notify:
    - restart ganglia-monitor


